### ISSUE TITLE
Running the sample code raises an error

### ISSUE THREAD

**Issue by BingusCoOfficial** [phoenixr-codes/bedrockpy#1]
The error is 
```Traceback (most recent call last):
  File "main.py", line 3, in <module>
    app = bedrock.Server(
AttributeError: module 'bedrock' has no attribute 'Server'
```
I'm sure you can see why this is a problem, I can't even start the server.

**Comment by phoenixr-codes** [comment]
Are you sure you have installed `bedrockpy` from pypi and not `bedrock`?

Run
```
pip uninstall bedrock
pip uninstall bedrockpy
pip install bedrock
```
and try to run it again.

If this does not fix your problem, please provide the info outputted by
`pip show bedrockpy`.

**Comment by phoenixr-codes** [comment]
Because you have not answered yet this issue is closed.

Feel free to re-open this issue.
